FROM cupy/cupy

RUN apt-get update && apt-get install -y sudo

ARG USERNAME=yuki
ARG GROUPNAME=yuki
ARG UID=1000
ARG GID=1000
ARG PASSWORD=yuki
RUN groupadd -g $GID $GROUPNAME && \
    useradd -m -s /bin/bash -u $UID -g $GID -G sudo $USERNAME && \
    echo $USERNAME:$PASSWORD | chpasswd && \
    echo "$USERNAME   ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER $USERNAME
WORKDIR /home/$USERNAME/

# 使い方例
# docker build -t scratch2/2.0 .
# docker run -u yuki --gpus all -it -v "/home/yuki/clone/deep-learning-from-scratch-2:/home/yuki/clone/deep-learning-from-scratch-2:rw" scratch2/2.0